galaxy_info:
  author: Russell Zachary Feeser
  description: Install and deploys or backups your vanilla Minecraft server
  company: IRIS7 and Alta3 Research

  license: MIT

  min_ansible_version: 2.8

  platforms:
  - name: Debian
    versions: all
  - name: Ubuntu
    versions: all

  galaxy_tags:
      - minecraft
      - games
      - game
      - gameserver
      - fun
      - home
      - helpful
      - ubuntu
      - debian

dependencies: []
  # List your role dependencies here, one per line. Be sure to remove the '[]' above,
  # if you add dependencies to this list.
